# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          The Citric
paginate:       5
baseurl:        ""
url:            "http://blog.lucafluri.ch"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Luca Fluri
  url:          http://lucafluri.ch
  email:        me@lucafluri.ch
  twitter:      lucafluri
  github:       lucafluri


# Gems
gems:
  - jekyll-paginate
  - jekyll-feed

show_drafts: false
